### ISSUE TITLE
Error: Region is missing

### ISSUE THREAD

**Issue by lvitaly** [hawkaa/serverless-dynalite-local#4]
Hi.
I have tried to use the `serverless-dynalite-local` plugin but got this error.

```
serverless-dynalite-local: Dynalite listening on http://localhost:1338
serverless-dynalite-local: Creating table jl-local-ColumnSettings
serverless-dynalite-local: Creating table jl-local-CommandRequests
serverless-dynalite-local: Creating table jl-local-CommandResults

 Error ---------------------------------------------------

  Error: Region is missing
      at default (/Users/vl/dev/git/jl-flights-ui/node_modules/@aws-sdk/config-resolver/dist/cjs/RegionConfig.js:10:15)
      at /Users/vl/dev/git/jl-flights-ui/node_modules/@aws-sdk/node-config-provider/dist/cjs/fromStatic.js:6:77
      at /Users/vl/dev/git/jl-flights-ui/node_modules/@aws-sdk/property-provider/dist/cjs/chain.js:20:28

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.53.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
```

Any ideas on how to fix it?
Thanks.

**Comment by lvitaly** [comment]
It looks like region should be also configurable for DynamoDbClient options.
https://github.com/sdd/serverless-dynalite/blob/5883f8abcb28349cf8d78edfa2a6f9af53b297a4/index.js#L86

**Comment by trygveaa** [comment]
If anyone is still wondering about this, you need to have a region defined in your local machines AWS config. Either by specifying region in the config file (~/.aws/config) for the current profile (`default` if `AWS_PROFILE isn't set), or by setting the environment variable `AWS_REGION` to a region (I don't think it matters what you set it to for this plugin, only that it's set).
